{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "4f6360c7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import time\n",
    "import requests\n",
    "from bs4 import BeautifulSoup as bs\n",
    "from sqlalchemy import create_engine, text\n",
    "import pymysql\n",
    "pymysql.install_as_MySQLdb()\n",
    "import pandas as pd\n",
    "from datetime import datetime"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "3de0fced",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['주식종목', '회사명', '종목코드', '업종', '주요제품', '상장일', '결산월', '대표자명', '홈페이지', '지역']\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>주식종목</th>\n",
       "      <th>회사명</th>\n",
       "      <th>종목코드</th>\n",
       "      <th>업종</th>\n",
       "      <th>주요제품</th>\n",
       "      <th>상장일</th>\n",
       "      <th>결산월</th>\n",
       "      <th>대표자명</th>\n",
       "      <th>홈페이지</th>\n",
       "      <th>지역</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>코스닥</td>\n",
       "      <td>나우로보틱스</td>\n",
       "      <td>45951</td>\n",
       "      <td>특수 목적용 기계 제조업</td>\n",
       "      <td>산업용로봇 및 로봇자동화시스템</td>\n",
       "      <td>2025-05-08</td>\n",
       "      <td>12월</td>\n",
       "      <td>이종주</td>\n",
       "      <td>http://naurobot.com</td>\n",
       "      <td>인천광역시</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>코스닥</td>\n",
       "      <td>에이아이코리아</td>\n",
       "      <td>36495</td>\n",
       "      <td>특수 목적용 기계 제조업</td>\n",
       "      <td>2차전지 중앙 전해액 공급시스템(CESS), 프로세스파이핑, 건식세정장비</td>\n",
       "      <td>2025-04-29</td>\n",
       "      <td>12월</td>\n",
       "      <td>안진호</td>\n",
       "      <td>http://www.aik.co.kr/</td>\n",
       "      <td>경기도</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>코스닥</td>\n",
       "      <td>쎄크</td>\n",
       "      <td>08118</td>\n",
       "      <td>일반 목적용 기계 제조업</td>\n",
       "      <td>X-ray 검사장비, LINAC, Tabletop SEM</td>\n",
       "      <td>2025-04-28</td>\n",
       "      <td>12월</td>\n",
       "      <td>김종현</td>\n",
       "      <td>http:///www.seceng.co.kr/</td>\n",
       "      <td>경기도</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>코스닥</td>\n",
       "      <td>한국피아이엠</td>\n",
       "      <td>44890</td>\n",
       "      <td>자동차 신품 부품 제조업</td>\n",
       "      <td>내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행...</td>\n",
       "      <td>2025-04-04</td>\n",
       "      <td>12월</td>\n",
       "      <td>송준호</td>\n",
       "      <td>http://www.pimkorea.com</td>\n",
       "      <td>대구광역시</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>코스닥</td>\n",
       "      <td>에이유브랜즈</td>\n",
       "      <td>48107</td>\n",
       "      <td>섬유, 의복, 신발 및 가죽제품 소매업</td>\n",
       "      <td>레인부츠, 스니커즈, 겨울화, 패션잡화 등</td>\n",
       "      <td>2025-04-03</td>\n",
       "      <td>12월</td>\n",
       "      <td>김지훈</td>\n",
       "      <td>http://aubrandz.irpage.co.kr</td>\n",
       "      <td>서울특별시</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2757</th>\n",
       "      <td>유가증권</td>\n",
       "      <td>유한양행</td>\n",
       "      <td>00010</td>\n",
       "      <td>의약품 제조업</td>\n",
       "      <td>의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...</td>\n",
       "      <td>1962-11-01</td>\n",
       "      <td>12월</td>\n",
       "      <td>대표이..</td>\n",
       "      <td>http://www.yuhan.co.kr</td>\n",
       "      <td>서울특별시</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2758</th>\n",
       "      <td>유가증권</td>\n",
       "      <td>CJ대한통운</td>\n",
       "      <td>00012</td>\n",
       "      <td>도로 화물 운송업</td>\n",
       "      <td>Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...</td>\n",
       "      <td>1956-07-02</td>\n",
       "      <td>12월</td>\n",
       "      <td>신영수..</td>\n",
       "      <td>http://www.cjlogistics.com</td>\n",
       "      <td>서울특별시</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2759</th>\n",
       "      <td>유가증권</td>\n",
       "      <td>경방</td>\n",
       "      <td>00005</td>\n",
       "      <td>종합 소매업</td>\n",
       "      <td>섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입</td>\n",
       "      <td>1956-03-03</td>\n",
       "      <td>12월</td>\n",
       "      <td>김준,..</td>\n",
       "      <td>http://www.kyungbang.co.kr</td>\n",
       "      <td>서울특별시</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2760</th>\n",
       "      <td>유가증권</td>\n",
       "      <td>유수홀딩스</td>\n",
       "      <td>00070</td>\n",
       "      <td>회사 본부 및 경영 컨설팅 서비스업</td>\n",
       "      <td>지주사업</td>\n",
       "      <td>1956-03-03</td>\n",
       "      <td>12월</td>\n",
       "      <td>송영규</td>\n",
       "      <td>http://www.eusu-holdings.com</td>\n",
       "      <td>서울특별시</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2761</th>\n",
       "      <td>유가증권</td>\n",
       "      <td>한진중공업홀딩스</td>\n",
       "      <td>00348</td>\n",
       "      <td>연료용 가스 제조 및 배관공급업</td>\n",
       "      <td>지주회사</td>\n",
       "      <td>1956-03-03</td>\n",
       "      <td>12월</td>\n",
       "      <td>조원국</td>\n",
       "      <td>http://www.hhic-holdings.com</td>\n",
       "      <td>경기도</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2762 rows × 10 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      주식종목       회사명   종목코드                     업종  \\\n",
       "0      코스닥    나우로보틱스  45951          특수 목적용 기계 제조업   \n",
       "1      코스닥   에이아이코리아  36495          특수 목적용 기계 제조업   \n",
       "2      코스닥        쎄크  08118          일반 목적용 기계 제조업   \n",
       "3      코스닥    한국피아이엠  44890          자동차 신품 부품 제조업   \n",
       "4      코스닥    에이유브랜즈  48107  섬유, 의복, 신발 및 가죽제품 소매업   \n",
       "...    ...       ...    ...                    ...   \n",
       "2757  유가증권      유한양행  00010                의약품 제조업   \n",
       "2758  유가증권    CJ대한통운  00012              도로 화물 운송업   \n",
       "2759  유가증권        경방  00005                 종합 소매업   \n",
       "2760  유가증권     유수홀딩스  00070    회사 본부 및 경영 컨설팅 서비스업   \n",
       "2761  유가증권  한진중공업홀딩스  00348      연료용 가스 제조 및 배관공급업   \n",
       "\n",
       "                                                   주요제품         상장일  결산월  \\\n",
       "0                                      산업용로봇 및 로봇자동화시스템  2025-05-08  12월   \n",
       "1              2차전지 중앙 전해액 공급시스템(CESS), 프로세스파이핑, 건식세정장비  2025-04-29  12월   \n",
       "2                       X-ray 검사장비, LINAC, Tabletop SEM  2025-04-28  12월   \n",
       "3     내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행...  2025-04-04  12월   \n",
       "4                               레인부츠, 스니커즈, 겨울화, 패션잡화 등  2025-04-03  12월   \n",
       "...                                                 ...         ...  ...   \n",
       "2757  의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...  1962-11-01  12월   \n",
       "2758  Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...  1956-07-02  12월   \n",
       "2759          섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입  1956-03-03  12월   \n",
       "2760                                               지주사업  1956-03-03  12월   \n",
       "2761                                               지주회사  1956-03-03  12월   \n",
       "\n",
       "       대표자명                          홈페이지     지역  \n",
       "0       이종주           http://naurobot.com  인천광역시  \n",
       "1       안진호         http://www.aik.co.kr/    경기도  \n",
       "2       김종현     http:///www.seceng.co.kr/    경기도  \n",
       "3       송준호       http://www.pimkorea.com  대구광역시  \n",
       "4       김지훈  http://aubrandz.irpage.co.kr  서울특별시  \n",
       "...     ...                           ...    ...  \n",
       "2757  대표이..        http://www.yuhan.co.kr  서울특별시  \n",
       "2758  신영수..    http://www.cjlogistics.com  서울특별시  \n",
       "2759  김준,..    http://www.kyungbang.co.kr  서울특별시  \n",
       "2760    송영규  http://www.eusu-holdings.com  서울특별시  \n",
       "2761    조원국  http://www.hhic-holdings.com    경기도  \n",
       "\n",
       "[2762 rows x 10 columns]"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "company_infos = []\n",
    "page = 1\n",
    "while True:\n",
    "    url =\"https://kind.krx.co.kr/corpgeneral/corpList.do\"\n",
    "    payload = dict(method=\"searchCorpList\", pageIndex=page,\n",
    "                 currentPageSize=100,\n",
    "                 orderMode=3, orderStat=\"D\", searchType=13,\n",
    "                 fiscalYearEnd=\"all\", location=\"all\")\n",
    "    r = requests.post(url, data=payload)\n",
    "#     print(r.status_code)\n",
    "    soup = bs(r.content, 'lxml')\n",
    "    # 전체 페이지\n",
    "    total_page = int(soup.select_one(\".info.type-00 > em\").text.replace(\",\", \"\")) // 100 + 1\n",
    "    \n",
    "    for idx, tr in enumerate(soup.select(\"tbody > tr\")):\n",
    "        print(f'{page}/{total_page}중, {idx}/{len(soup.select(\"tbody > tr\"))} 작업중', end=\"\\r\")\n",
    "        # 주식종목\n",
    "        stock_type = tr.select_one(\"td:nth-child(1) > img\")['alt']\n",
    "        # 회사이름\n",
    "        company_name = tr.select_one(\"td:nth-child(1) > a\")[\"title\"]\n",
    "        # 종목코드\n",
    "        stock_code = tr.select_one(\"td:nth-child(1) > a\")[\"onclick\"].split(\"'\")[1]\n",
    "        # 업종\n",
    "        business_type = tr.select_one(\"td:nth-child(2)\").text\n",
    "        # 주요제품\n",
    "        product = tr.select_one(\"td:nth-child(3)\").text\n",
    "        # 상장일\n",
    "        resi_date = tr.select_one(\"td:nth-child(4)\").text\n",
    "        # 결산월\n",
    "        settlement = tr.select_one(\"td:nth-child(5)\").text\n",
    "        # 대표자명\n",
    "        ceo = tr.select_one(\"td:nth-child(6)\").text\n",
    "        # 홈페이지(url)\n",
    "        hompage = tr.select_one(\"td:nth-child(7) > a\")[\"href\"] if tr.select_one(\"td:nth-child(7) > a\") != None else \"\"\n",
    "        # 지역\n",
    "        region = tr.select_one(\"td:nth-child(8)\").text\n",
    "        company_infos.append((stock_type, company_name, stock_code, business_type,\n",
    "                            product, resi_date, settlement, ceo, hompage, region))\n",
    "\n",
    "    if page < total_page:\n",
    "        page += 1\n",
    "    else:\n",
    "        break\n",
    "    \n",
    "# 컬럼명\n",
    "columns = soup.select_one(\"table\")[\"summary\"].split(\", \")\n",
    "columns.insert(0, \"주식종목\")\n",
    "columns.insert(2, \"종목코드\")\n",
    "print(columns)\n",
    "korean_stock = pd.DataFrame(company_infos, columns=columns)\n",
    "korean_stock"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "d01a1d8c",
   "metadata": {},
   "outputs": [],
   "source": [
    "engine = create_engine(\"mysql+pymysql://root:1234@localhost:3306/korean_stock\")\n",
    "conn = engine.connect()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "56ecd60e",
   "metadata": {},
   "outputs": [],
   "source": [
    "korean_stock.to_sql(\"company_info\", con=conn, if_exists='replace', index=False)\n",
    "conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "d3348d0a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'key': None}\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "\n",
    "# 예제\n",
    "data = '{\"key\": null}'\n",
    "parsed_data = json.loads(data)\n",
    "print(parsed_data)  # {'key': None}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2444716a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.21"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
